#!/usr/bin/env bash

####################################################
## Library
function find_phpunits() {
  for n in phpunit{4,5,6,7,8,9} ; do
    if [ -f "$BKIT/extern/$n/$n.phar" ]; then
      echo "$n"
    fi
  done
}

function show_project_cfg() {
  echo "Project Preferences:"
  echo "    PHP: Register the interpreter:"
  echo "        $PHP"
  echo "    PHP: Register one of these include paths:"
  for PHPUNIT in $PHPUNITS ; do
    echo "        $BKIT/extern/$PHPUNIT"
  done
  echo "    Test Frameworks/PHPUnit: Register one of these PHARs:"
  for PHPUNIT in $PHPUNITS ; do
    echo "        $BKIT/extern/$PHPUNIT/$PHPUNIT.phar"
  done
  echo
}

function show_run_cfg() {
  echo "Run: Edit Configuration"
  echo "    Defaults/Templates: PHPUnit:"
  echo "        Alternative configuration file:"
  echo "            $CIVI_CORE/phpunit.xml.dist"
  echo "        Custom working directory:"
  echo "            $CIVI_CORE"
  echo "        Environment variables:"
  echo "            CIVICRM_UF=UnitTests"
  echo "            PATH=$PATH"
  echo
}

####################################################
## Main
if [ -z "$LOCO_PRJ" ]; then
  echo "Please run this within bknix."
  exit 1
fi

PHP=$(which php)
PHPUNITS=$(find_phpunits)

echo "Key details for configuring PhpStorm to run unit-tests:"
echo

show_project_cfg

BLDNAME="$1"
if [ -z "$BLDNAME" ]; then
  echo "TIP: To see full phpunit options, specify the name of the target build, e.g."
  echo "  $0 dmaster"
elif [ ! -f "$HTTPD_VDROOT/$BLDNAME.sh" ]; then
  echo "WARNING: Cannot show full phpunit options. Failed to find $HTTPD_VDROOT/$BLDNAME.sh"
else
  source "$HTTPD_VDROOT/$BLDNAME.sh"
  show_run_cfg
fi
