#!/usr/bin/env bash
set -e

## Example usage:
##
## $ env ghprbTargetBranch=master ghprbPullId=307 run-bknix-job --mock dfl CiviCRM-WordPress-Style

#################################################

assert_common ghprbTargetBranch
case "$ghprbTargetBranch" in
  5.30|5.31|5.32)
    echo "Skip style tests in civicrm-wordpress circa 5.31-5.32"
    exit 0
    ;;
esac

#################################################

CIVI_REPO=civicrm-wordpress
run_bknix_include "$BKNIX_JOBS/Generic-Style.job"
