#!/usr/bin/env bash
set -e

## Example usage:
##
## $ env ghprbTargetBranch=7.x-master ghprbPullId=673 run-bknix-job --mock dfl CiviCRM-Drupal-Test

#################################################

CIVI_REPO=civicrm-drupal
BLDTYPE=drupal-clean
SUITES='upgrade phpunit-e2e phpunit-drupal'
#SUITES='upgrade karma phpunit-e2e phpunit-drupal'
#SUITES='phpunit-drupal'

run_job_include "$BKNIX_JOBS/Generic-Test.job"
